apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 020866158197.dkr.ecr.us-east-1.amazonaws.com/calories-burnt-pred-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CALORIES_BURNT_PRED
          valueFrom:
            secretKeyRef:
              name: calories-secret
              key: CALORIES_BURNT_PRED
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: calories-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: calories-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: calories-secret
              key: AWS_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: calories-secret
              key: S3_BUCKET_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
